# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_value', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Jean',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Brand')),
                ('colors', models.ManyToManyField(to='products.Color')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist', models.CharField(max_length=2)),
                ('length', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_type', models.CharField(max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name='jean',
            name='sizes',
            field=models.ManyToManyField(to='products.Size'),
        ),
        migrations.AddField(
            model_name='jean',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Style'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='products.ProductImage'),
        ),
    ]
