# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170303_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='products.ProductImage'),
        ),
    ]
