# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='products.ProductImage'),
        ),
    ]
